TARGET_COMPANIES = [
    {"name": "Laurus Labs", "scrip_code": "540222", "sector": "CDMO / API"},
    {"name": "Divi's Laboratories", "scrip_code": "532488", "sector": "CDMO / API"},
    {"name": "Syngene International", "scrip_code": "539268", "sector": "CDMO"},
    {"name": "Piramal Pharma", "scrip_code": "543635", "sector": "CDMO / Formulations"},
    {"name": "Cohance Lifesciences", "scrip_code": "543350", "sector": "CDMO"},
    {"name": "Anthem Biosciences", "scrip_code": "544210", "sector": "CDMO"},
    {"name": "Sai Life Sciences", "scrip_code": "544282", "sector": "CDMO"},
    {"name": "Neuland Laboratories", "scrip_code": "524558", "sector": "API"},
    {"name": "Sun Pharmaceutical", "scrip_code": "524715", "sector": "Formulations"},
    {"name": "Dr. Reddy's Laboratories", "scrip_code": "500124", "sector": "Formulations"},
    {"name": "Cipla", "scrip_code": "500087", "sector": "Formulations"},
    {"name": "Lupin", "scrip_code": "500257", "sector": "Formulations"},
    {"name": "Mankind Pharma", "scrip_code": "543904", "sector": "Domestic Formulations"},
    {"name": "Torrent Pharmaceuticals", "scrip_code": "500420", "sector": "Domestic Formulations"},
    {"name": "Alkem Laboratories", "scrip_code": "539523", "sector": "Domestic Formulations"},
    {"name": "Ipca Laboratories", "scrip_code": "524494", "sector": "Domestic Formulations"},
    {"name": "Max Healthcare", "scrip_code": "543220", "sector": "Hospitals"},
    {"name": "Apollo Hospitals", "scrip_code": "508869", "sector": "Hospitals"},
    {"name": "Narayana Hrudayalaya", "scrip_code": "539551", "sector": "Hospitals"},
    {"name": "Fortis Healthcare", "scrip_code": "532843", "sector": "Hospitals"},
    {"name": "Metropolis Healthcare", "scrip_code": "542650", "sector": "Diagnostics"},
    {"name": "Dr. Lal PathLabs", "scrip_code": "539524", "sector": "Diagnostics"},
    {"name": "Thyrocare Technologies", "scrip_code": "539871", "sector": "Diagnostics"},
    {"name": "MedPlus Health Services", "scrip_code": "543741", "sector": "Pharmacy Retail"},
    {"name": "Poly Medicure", "scrip_code": "531768", "sector": "Med Devices"},
    {"name": "Infosys", "scrip_code": "500209", "sector": "IT (benchmark)"},
    {"name": "TCS", "scrip_code": "532540", "sector": "IT (benchmark)"},
    {"name": "HDFC Bank", "scrip_code": "500180", "sector": "BFSI (benchmark)"},
    {"name": "Reliance Industries", "scrip_code": "500325", "sector": "Conglomerate (benchmark)"},
    {"name": "Asian Paints", "scrip_code": "500820", "sector": "Consumer (benchmark)"},
]
